### ISSUE TITLE
Getting playlists

### ISSUE THREAD

**Issue by promotion** [norkunas/youtube-dl-php#133]
Hi, 
any chance of getting playlists ? (just plaint ext of name/link/playlist name) ?
Maybe you schedule this to future releases ?

**Comment by norkunas** [comment]
Hello.
Currently there is no way, because my target was single videos when I made this library.
If you need it, extend the YoutubeDl class and run the process with `youtube-dl --flat-playlist YOUR_PLAYLIST_URL`.
I see there is a new option `dump-single-json` so I'll think about supporting playlists also.

**Comment by norkunas** [comment]
Playlist support landed in master.
