### ISSUE TITLE
Can't set environment variable for process on Windows OS 

### ISSUE THREAD

**Issue by cadlec** [norkunas/youtube-dl-php#198]
Hi!...I've got the error #39 too. And after setting the bin path and python path, it didn't work.

But, I've been able to fix the error by adding this code in DefaultProcessBuilder.php file:

`$process = new Process($arguments, null, [
    'SYSTEMROOT' => 'C:\WINDOWS',
 ])`

So, I think we need a way to set the Windows environment variable in order to fix definitely this error.  
My proposition is to create a setter for this environment variable.
Thanks

**Comment by norkunas** [comment]
Hello,

Reading [Symfony Process Docs](https://symfony.com/doc/current/components/process.html#setting-environment-variables-for-processes) there is a note:

> In addition to the env vars passed explicitly, processes **inherit all the env vars defined in your system**. You can prevent this by setting to false the env vars you want to remove

So this shouldn't be needed. You should look for a reason why it doesn't inherit it.

**Comment by norkunas** [comment]
But anyway, as a workaround instead of patching `DefaultProcessBuilder` you could just implement a custom `YoutubeDl\Process\ProcessBuilderInterface` where you set your env vars and then provide it to `YoutubeDl` as a first argument when constructing, to ensure that it will work always for you even after `composer update`.

**Comment by cadlec** [comment]
Thank you @norkunas , your workaround is what I've did and it worked !
