### ISSUE TITLE
Parse error: syntax error, unexpected ':', expecting ';' or '{' in C:\wamp\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php on line 517

### ISSUE THREAD

**Issue by rodzky** [norkunas/youtube-dl-php#34]
Please help, I got this error after trying to download audio/video.

![youtube-dl error](https://cloud.githubusercontent.com/assets/26499880/24070230/2090a980-0bf4-11e7-8bc0-d07c8086fa8d.JPG)

Regards,
Rodelbert

**Comment by norkunas** [comment]
@rodzky i've fixed and released v0.3.3, please update.

**Comment by rodzky** [comment]
@norkunas thanks for prompt reply, I updated but I got a new error
![image](https://cloud.githubusercontent.com/assets/26499880/24071012/3b75d6c6-0c03-11e7-99d3-d4396544d4ca.png)

**Comment by norkunas** [comment]
http://stackoverflow.com/questions/30296288/php-warning-proc-open-createprocess-failed-error-code-267

**Comment by rodzky** [comment]
Thank you for that, I updated the download path but another error occured.
![image](https://cloud.githubusercontent.com/assets/26499880/24076090/04133d5c-0c64-11e7-9b5d-546f3466c20d.png)

I have both youtube-dl and ffmpeg properly installed on my local:
![image](https://cloud.githubusercontent.com/assets/26499880/24076102/25762720-0c64-11e7-935b-e1e57293c1ff.png)

![image](https://cloud.githubusercontent.com/assets/26499880/24076108/3c3fd12c-0c64-11e7-8d37-ae237dcd8571.png)

**Comment by norkunas** [comment]
Is it added to your environment variables?

2017-03-18 23:23 "rodzky" <notifications@github.com> rašė:

Thank you for that, I updated the download path but another error occured.
[image: image]
<https://cloud.githubusercontent.com/assets/26499880/24076090/04133d5c-0c64-11e7-9b5d-546f3466c20d.png>

I have both youtube-dl and ffmpeg properly installed on my local:
[image: image]
<https://cloud.githubusercontent.com/assets/26499880/24076102/25762720-0c64-11e7-935b-e1e57293c1ff.png>

[image: image]
<https://cloud.githubusercontent.com/assets/26499880/24076108/3c3fd12c-0c64-11e7-8d37-ae237dcd8571.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/norkunas/youtube-dl-php/issues/34#issuecomment-287575852>,
or mute the thread

**Comment by jovixv** [comment]
$process->setEnv(['LANG' => 'en_US.UTF-8']); this line in YoutubeDl.php, can create problem if you use windows
