### ISSUE TITLE
Failed to detect metadata file

### ISSUE THREAD

**Issue by kminek** [norkunas/youtube-dl-php#54]
Hi there,

here is my sample code which works fine with `0.3` version:

```php
$simulate = new \YoutubeDl\YoutubeDl(['simulate' => true]);
$simulate->setDownloadPath(__DIR__);
$video = $simulate->download('https://www.youtube.com/watch?v=nfWlot6h_JM');
dump($video);
```

however above code with `1.0` version gives following error:

```
Failed to detect metadata file. {"exception":"[object] (YoutubeDl\\Exception\\YoutubeDlException(code: 0): Failed to detect metadata file. at /app/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php:184)
```

i'm using quite recent `youtube-dl` version: `2017.11.15`

let me know if you need any additional info :)

**Comment by norkunas** [comment]
Hey @kminek, this is because internally lib uses `write-info-json` option which writes the metadata to the json file and then builds `YoutubeDl\Entity\Video` object from it, so if you are simulating and no metadata is created then it won't return the object. That option allows to integrate the progress callback. I know this is a BC break but 1.0 is a major release and some people asked for progress callback so it's just how it works now.

I see the only way to make `simulate` option working to disable `write-info-json` in case if you want to simulate it.. But it just doesn't feel right to do this, maybe it's better to remove `simulate` from allowed options unless you have a good use case.

**Comment by kminek** [comment]
i see. well i was using "simulate" code to decide whether i would like to download the video (based on its length in seconds for instance). i think it is quite common case to check video properties before deciding to download it. well i look into the 1.0 version code deeper to see what can i do about it :)

**Comment by norkunas** [comment]
There is another option `skip-download` it should work for your case :)

**Comment by kminek** [comment]
yeah, `skip-download` did the trick - thanks! :)
